###
# Install GeoServer from Custom GeoNode Build
#
---

- name: ensure apt cache is up to date
  apt: update_cache=yes
  become: yes

- name: install Tomcat
  apt: pkg={{ item }} state=present
  become: yes
  with_items:
   - tomcat8
   - unzip

- name: increase catalina memory size
  become: yes
  lineinfile:
    dest: /etc/default/tomcat8
    regexp: '^\s*JAVA_OPTS\s*=.*$'
    line: 'JAVA_OPTS="-Djava.awt.headless=true -Xms1024M -Xmx2096M -XX:MaxPermSize=1024m -XX:PermSize=512m -XX:+UseConcMarkSweepGC"'

- name: download GeoServer (remote)
  become: yes
  get_url:
    dest=/var/lib/tomcat8/webapps/geoserver.war
    url={{ geoserver_url }}
    owner=0
    group=0
    mode=0644

- name: wait for GeoServer to be unpacked
  wait_for:
    path: /var/lib/tomcat8/webapps/geoserver/data/global.xml
  become: yes

### oAuth setup part
- name: stopping Tomcat
  become: yes
  when: geoserver_url == "http://build.geonode.org/geoserver/latest/geoserver-2.9.x-oauth2.war"
  service:
    name: tomcat8
    state: stopped

- name: remove default data folder if oauth2 GeoServer used
  become: yes
  when: geoserver_url == "http://build.geonode.org/geoserver/latest/geoserver-2.9.x-oauth2.war"
  file:
    path: /var/lib/tomcat8/webapps/geoserver/data
    state: absent

- name: download oauth2 data folder (remote)
  become: yes
  when: geoserver_url == "http://build.geonode.org/geoserver/latest/geoserver-2.9.x-oauth2.war"
  get_url:
    dest=/var/lib/tomcat8/webapps/geoserver/data.zip
    url={{ geoserver_data_url }}
    owner=0
    group=0
    mode=0644

- name: wait for data file to be downloaded
  when: geoserver_url == "http://build.geonode.org/geoserver/latest/geoserver-2.9.x-oauth2.war"
  wait_for:
    path: /var/lib/tomcat8/webapps/geoserver/data.zip
  become: yes

- name: unzip oauth2 data folder
  become: yes
  when: geoserver_url == "http://build.geonode.org/geoserver/latest/geoserver-2.9.x-oauth2.war"
  shell: "cd /var/lib/tomcat8/webapps/geoserver && unzip data.zip && chown -R tomcat8:tomcat8 data"

- name: remove data.zip
  become: yes
  when: geoserver_url == "http://build.geonode.org/geoserver/latest/geoserver-2.9.x-oauth2.war"
  file:
    path: /var/lib/tomcat8/webapps/geoserver/data.zip
    state: absent

- name: check if logstore file exists
  stat:
    path: /var/lib/tomcat8/webapps/geoserver/data/geogig/config/security/logstore.properties
  register: logstore_file
  become: yes

- name: adding sqlite logstore setting
  become: yes
  when: logstore_file.stat.exists
  lineinfile:
    dest: "/var/lib/tomcat8/webapps/geoserver/data/geogig/config/security/logstore.properties"
    regexp: "^url="
    line: "url=jdbc:sqlite://var/lib/tomcat8/webapps/geoserver/data/geogig/config/security/securitylogs.db"
    state: "present"

- name: check if geonode-oauth file exists
  stat:
    path: /var/lib/tomcat8/webapps/geoserver/data/security/filter/geonode-oauth2/config.xml
  register: geonode_oauth_file
  become: yes

- name: patch the geonode-oauth file (geoserver part)
  become: yes
  shell: sed -i -e "s|http://localhost:8080|http://{{ server_name }}|g" /var/lib/tomcat8/webapps/geoserver/data/security/filter/geonode-oauth2/config.xml
  when: geonode_oauth_file.stat.exists

- name: patch the geonode-oauth file (geonode part)
  become: yes
  shell: sed -i -e "s|http://localhost:8000|http://{{ server_name }}|g" /var/lib/tomcat8/webapps/geoserver/data/security/filter/geonode-oauth2/config.xml
  when: geonode_oauth_file.stat.exists

- name: patch the geonode-role file
  become: yes
  shell: sed -i -e "s|http://localhost:8000|http://{{ server_name }}|g" /var/lib/tomcat8/webapps/geoserver/data/security/role/geonode\ REST\ role\ service/config.xml
  when: geonode_oauth_file.stat.exists

- name: patch the geoserver global config file
  become: yes
  shell: sed -i -e "s|http://localhost:8080|http://{{ server_name }}|g" /var/lib/tomcat8/webapps/geoserver/data/global.xml
  when: geonode_oauth_file.stat.exists

- name: remove masterpw.info file to remove security risk warning
  become: yes
  file:
    path: /var/lib/tomcat8/webapps/geoserver/data/security/masterpw.info
    state: absent

- name: set digest password encoding
  become: yes
  lineinfile:
    dest: /var/lib/tomcat8/webapps/geoserver/data/security/usergroup/default/config.xml
    regexp: '\s*<passwordEncoderName>.*'
    line: '  <passwordEncoderName>digestPasswordEncoder</passwordEncoderName>'

- name: Remove PostgreSQL 8.4 JDBC driver - see https://github.com/geonetwork/core-geonetwork/issues/1887
  file:
    path: /var/lib/tomcat8/webapps/geoserver/WEB-INF/lib/postgresql-8.4-702.jdbc3.jar
    state: absent
  become: yes

- name: Remove PostGIS stubs for the same reason
  file:
    path: /var/lib/tomcat8/webapps/geoserver/WEB-INF/lib/postgis-stubs-1.3.3.jar
    state: absent
  become: yes

- name: restarting Tomcat
  become: yes
  service:
    name: tomcat8
    state: restarted
